name: vmate
description: State management with MVVM pattern
version: 0.0.3
homepage: https://github.com/elliotkhd/vmate

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
